name: Auto Assign to Project

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Turbopy-Bootcamp Project
    steps:
    - name: Assign issues and pull requests (fundamental/applied python, curriculum, general seminar) to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'applied python') ||
        contains(github.event.pull_request_target.labels.*.name, 'applied python') ||
        contains(github.event.issue.labels.*.name, 'fundamental python') ||
        contains(github.event.pull_request_target.labels.*.name, 'fundamental python') ||
        contains(github.event.issue.labels.*.name, 'general seminar') ||
        contains(github.event.pull_request_target.labels.*.name, 'general seminar') ||
        contains(github.event.issue.labels.*.name, 'curriculum') ||
        contains(github.event.pull_request_target.labels.*.name, 'curriculum')
      with:
        project: 'https://github.com/NRL-Plasma-Physics-Division/turbopy-bootcamp/projects/1'
